vim-tmux-clipboard is using vim-tmux-focus-events
tmux-plugins/vim-tmux-focus-events pull request #9
Opened 2016-07-30 00:50 UTC by roxma

2016-09-24 19:53 UTC, ericboehs commented on README.md
> +- [vim-tmux-clipboard](https://github.com/roxma/vim-tmux-focus-events) uses
I think you meant to link to https://github.com/roxma/vim-tmux-clipboard

2016-09-24 19:53 UTC, ericboehs requested changes

2016-09-25 01:59 UTC, roxma reviewed
Opps, my mistake.

2017-09-21 10:48 UTC, merged

2017-09-21 10:48 UTC, bruno- commented
Sorry for waiting so long on merging this.